# Generated by Django 5.1.3 on 2025-01-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_educationalqualification_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='nid_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
