# Generated by Django 5.1.3 on 2025-01-04 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0003_alter_institute_options_alter_studyclass_options'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_institute', to='authority.institute'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='study_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_class', to='authority.studyclass'),
        ),
    ]
