# Generated by Django 5.1.3 on 2025-01-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyclass',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
