# Generated by Django 5.1.3 on 2025-01-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0003_alter_institute_options_alter_studyclass_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('published_status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default='published', max_length=15)),
                ('published_for', models.CharField(choices=[('all', 'All'), ('teacher', 'Teacher'), ('student', 'Student')], default='all', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
