# Generated by Django 5.1.3 on 2025-01-06 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0004_notice'),
        ('teacher', '0003_teacherprofile_nid_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_name', models.CharField(max_length=255, unique=True)),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_fee', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_name', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('maximum_students', models.PositiveIntegerField()),
                ('course_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructor', to='teacher.teacherprofile')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_class', to='authority.studyclass')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_course', to='authority.course')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batch',
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
    ]
