# Generated by Django 5.1.3 on 2025-01-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0006_weekdays_batch_class_per_week_batch_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
