# Generated by Django 5.1.3 on 2025-01-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0007_alter_weekdays_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
