# Generated by Django 5.1.3 on 2025-01-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0008_course_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekdays',
            options={'ordering': ('-id',), 'verbose_name': 'Week Days'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
