# Generated by Django 5.1.3 on 2025-01-12 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0009_alter_weekdays_options_alter_batch_is_active'),
        ('student', '0002_alter_studentprofile_institute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_batch', to='authority.batch')),
                ('enrolled_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_enrolled_student', to='student.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
