# Generated by Django 5.1.3 on 2025-01-14 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0010_enrolledstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='assignment/')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_batch', to='authority.batch')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignment',
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
    ]
