# Generated by Django 5.1.3 on 2025-01-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0012_submittedassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignment',
            name='review_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment/'),
        ),
    ]
