# Generated by Django 5.1.3 on 2025-01-17 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0013_submittedassignment_review_file'),
        ('student', '0002_alter_studentprofile_institute_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submittedassignment',
            options={'ordering': ('-id',), 'verbose_name': 'Submitted Assignment', 'verbose_name_plural': 'Submitted Assignment'},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_date', models.DateField()),
                ('is_present', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_batch', to='authority.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_student', to='student.studentprofile')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'unique_together': {('batch', 'student', 'attendance_date')},
            },
        ),
    ]
